files:
  - source: /udata_front/theme/gouvpt/translations/gouvpt.pot
    translation: >-
      /udata_front/theme/gouvpt/translations/%two_letters_code%/LC_MESSAGES/%file_name%.po
  - source: /theme/js/locales/en.json
    translation: /theme/js/locales/%two_letters_code%.json
